import { escape, icon, money } from './ui.js';
import { getOfficeOverview } from './office-progression.js';
import { getFinanceOverview, getCashForecast, getCreditOverview, getPayroll, getReceivableRisk, getReceivableAction,
  getMonthlyStatement, EXPENSE_LABELS, FINANCE_CYCLE, TAX_RATE, periodId } from './finance-model.js';

const SECTIONS = [['main', 'Caixa e fôlego'], ['forecast', 'Fluxo previsto'], ['receivables', 'A receber'], ['payables', 'A pagar'], ['credit', 'Crédito'], ['monthly', 'Fechamento']];
const signMoney = n => `${n >= 0 ? '+' : '−'}${money(Math.abs(n))}`;
const percent = n => `${(n * 100).toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%`;
const empty = text => `<div class="finance-empty">${escape(text)}</div>`;
const note = text => `<p class="finance-note">${escape(text)}</p>`;
const metric = (label, value, detail, cls = '') => `<div class="finance-metric ${cls}"><small>${escape(label)}</small><strong>${escape(value)}</strong>${detail ? `<span>${escape(detail)}</span>` : ''}</div>`;

function lineChart(points, comparison = null, label = 'Projeção do saldo', color = '#35735e') {
  const compact = typeof window !== 'undefined' && window.innerWidth <= 760;
  const w = compact ? Math.max(250, window.innerWidth - 70) : 660, h = compact ? 200 : 225, left = compact ? 64 : 74, right = 18, top = 22, bottom = 32;
  const values = [...points, ...(comparison || [])].map(p => p.balance);
  const low = Math.min(0, ...values), high = Math.max(1, ...values);
  const range = high - low || 1, min = low - range * .08, max = high + range * .1;
  const x = i => left + i / Math.max(1, points.length - 1) * (w - left - right);
  const y = value => top + (max - value) / (max - min) * (h - top - bottom);
  const path = list => list.map((p, i) => `${i ? 'L' : 'M'}${x(i).toFixed(1)},${y(p.balance).toFixed(1)}`).join(' ');
  const grid = Array.from({ length: 4 }, (_, i) => {
    const value = min + (max - min) * i / 3;
    return `<line x1="${left}" x2="${w-right}" y1="${y(value)}" y2="${y(value)}" stroke="#d4d9ca"/><text x="${left-9}" y="${y(value)+4}" text-anchor="end">${escape(money(value))}</text>`;
  }).join('');
  const risk = comparison && comparison.some((p, i) => p.balance !== points[i]?.balance);
  return `<div class="finance-chart"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${escape(label)}">${grid}<line x1="${left}" x2="${w-right}" y1="${y(0)}" y2="${y(0)}" stroke="#b47b62" stroke-dasharray="4 4"/><path d="${path(points)}" fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round"/>${risk ? `<path d="${path(comparison)}" fill="none" stroke="#b77746" stroke-width="2" stroke-dasharray="6 5"/>` : ''}${points.map((p, i) => `<circle cx="${x(i)}" cy="${y(p.balance)}" r="3" fill="${color}"><title>D${p.day}: ${escape(money(p.balance))}</title></circle>`).join('')}${[0, Math.floor((points.length-1)/2), points.length-1].map(i => `<text x="${x(i)}" y="${h-7}" text-anchor="middle">D${points[i].day}</text>`).join('')}</svg><div class="finance-chart-legend"><span><i style="background:${color}"></i>${escape(label)}</span>${risk ? '<span><i class="risk-line"></i>Sem os clientes de alto risco</span>' : ''}</div></div>`;
}
function bars(rows) {
  const max = Math.max(1, ...rows.map(row => row.value));
  return `<div class="finance-bars">${rows.map(row => `<div class="finance-bar-row"><span>${escape(row.label)}</span><div><i style="width:${Math.max(0, row.value / max * 100)}%;background:${row.color || '#5a7969'}"></i></div><strong>${money(row.value)}</strong></div>`).join('')}</div>`;
}
function ledger(state) {
  return `<section class="finance-paper"><div class="finance-section-title"><h3>Extrato de caixa</h3><button data-station-tab="main">Voltar ao resumo</button></div><div class="finance-table-wrap"><table class="finance-table"><thead><tr><th>Dia</th><th>Movimentação</th><th>Valor</th></tr></thead><tbody>${state.ledger.slice(0, 60).map(e => `<tr><td>D${e.day}</td><td>${escape(e.label)}</td><td class="${e.amount >= 0 ? 'finance-positive' : 'finance-negative'}">${signMoney(e.amount)}</td></tr>`).join('')}</tbody></table></div></section>`;
}
function overview(state, data) {
  const future = data.forecast, end = state.day + 29;
  const history = state.history.slice(-30).map(h => ({ day: h.day, balance: h.cash }));
  if (history.at(-1)?.balance !== state.cash) history.push({ day: state.day, balance: state.cash });
  return `<div class="finance-page-heading"><h2>Caixa e fôlego</h2><button data-station-tab="ledger">Extrato de caixa ${icon('arrow')}</button></div><div class="finance-two-columns"><section class="finance-paper"><h3>Até onde o caixa vai?</h3>${metric('Fôlego sem novas entradas', `${data.runwayCapped ? 'Mais de ' : ''}${data.runway} dias`, `Despesas médias: ${money(data.dailyBurn)}/dia`, data.runway < 7 ? 'danger' : '')}<div class="finance-runway-track"><span style="width:${Math.min(100, data.runway / 30 * 100)}%"></span></div><div class="finance-runway-scale"><span>0</span><span>15 dias</span><span>30+ dias</span></div>${note('Inclui salários nos dias úteis, encargos, aluguel, serviços, manutenção e impostos já provisionados. Não depende de contratos ainda não entregues.')}</section><section class="finance-paper finance-forecast-note"><small>PREVISÃO ATÉ D${end}</small><strong class="${future.closingBalance < 0 ? 'finance-negative' : ''}">${money(future.closingBalance)}</strong><p>Entradas: <b>${money(future.incoming)}</b><br>Saídas: <b>${money(future.outgoing)}</b></p>${future.firstNegativeDay ? `<div class="finance-warning">Caixa negativo previsto em D${future.firstNegativeDay}. Confira as cobranças ou o crédito.</div>` : '<div class="finance-stamp">Caixa positivo nos próximos 30 dias</div>'}<button data-station-tab="forecast">Abrir fluxo previsto ${icon('arrow')}</button></section></div><section class="finance-paper"><div class="finance-section-title"><h3>O que vem por aí</h3><button data-station-tab="payables">Ver contas a pagar</button></div>${data.upcoming.length ? `<div class="finance-agenda">${data.upcoming.map(day => `<button data-finance-day="${day.day}"><span>D${day.day}</span><div>${day.events.filter(e => e.amount > 0 || ['maintenance', 'tax', 'interest'].includes(e.category)).map(e => `<small>${escape(e.label)} · ${e.debtIncrease ? `${money(e.debtIncrease)} na dívida` : signMoney(e.amount)}</small>`).join('')}</div>${icon('arrow')}</button>`).join('')}</div>` : empty('Nenhum recebimento ou débito pontual previsto. Aluguel e folha continuam na rotina.')}</section><section class="finance-paper"><h3>Caixa realizado</h3>${history.length > 1 ? lineChart(history, null, 'Saldo ao fechar os dias') : empty('O histórico aparece após o primeiro fechamento de dia.')}</section>`;
}
function forecast(state, data, selectedDay) {
  const expected = data.forecast, stress = getCashForecast(state, 30, true, true);
  const selected = expected.daily.find(d => d.day === selectedDay) || expected.daily[0];
  return `<div class="finance-page-heading"><h2>Fluxo previsto · 30 dias</h2><span>D${state.day} — D${state.day+29}</span></div><div class="finance-compact-metrics">${metric('Entradas previstas', money(expected.incoming))}${metric('Saídas previstas', money(expected.outgoing))}${metric('Menor saldo', money(expected.minBalance), expected.firstNegativeDay ? `Primeiro dia no vermelho: D${expected.firstNegativeDay}` : 'Sem saldo negativo no período', expected.minBalance < 0 ? 'danger' : '')}</div><section class="finance-paper">${lineChart(expected.points, stress.points)}${note('Considera recebíveis já emitidos e o produto lançado. Projetos em andamento e novos contratos entram somente após a entrega. O cenário de risco exclui clientes de alto risco; entradas previstas não são dinheiro garantido. Juros capitalizados aumentam a dívida, sem débito imediato no caixa.')}</section><nav class="finance-day-strip" aria-label="Dia da previsão">${expected.daily.map(d => `<button class="${d.day === selected.day ? 'active' : ''} ${d.balance < 0 ? 'negative' : ''}" data-finance-day="${d.day}" aria-pressed="${d.day === selected.day}"><span>D${d.day}</span><small>${d.incoming ? '+' : '−'}</small></button>`).join('')}</nav><section class="finance-paper"><div class="finance-section-title"><h3>Agenda de D${selected.day}</h3><strong>Saldo previsto: ${money(selected.balance)}</strong></div><div class="finance-table-wrap"><table class="finance-table"><thead><tr><th>Compromisso</th><th>Entrada / saída</th></tr></thead><tbody>${selected.events.map(e => `<tr><td>${escape(e.label)}</td><td class="${e.amount > 0 ? 'finance-positive' : 'finance-negative'}">${e.debtIncrease ? `${money(e.debtIncrease)} na dívida` : signMoney(e.amount)}</td></tr>`).join('')}</tbody></table></div></section>`;
}
function receivables(state) {
  return `<div class="finance-page-heading"><h2>A receber</h2><span>${state.receivables.length} títulos</span></div>${state.receivables.map(r => {
    const risk = getReceivableRisk(state, r), project = state.projects.find(p => p.id === r.projectId);
    const collect = getReceivableAction(state, r, 'collect'), firm = getReceivableAction(state, r, 'firm');
    const anticipate = getReceivableAction(state, r, 'anticipate'), renegotiate = getReceivableAction(state, r, 'renegotiate');
    const status = risk.defaulted ? 'Calote · baixado' : risk.late ? 'Vencido' : r.renegotiated ? 'Renegociado' : 'A vencer';
    return `<article class="finance-paper finance-invoice" data-finance-invoice="${escape(r.projectId)}"><header><div><small>${escape(project?.title || 'Projeto entregue')}</small><h3>${escape(r.client)}</h3></div><strong>${money(r.amount)}</strong></header><div class="finance-invoice-details"><span class="finance-status ${risk.defaulted || risk.late ? 'late' : ''}">${status}</span><span>Vencimento D${r.dueDay}</span><span>Previsão ${risk.defaulted ? 'sem recebimento' : `D${risk.expectedDay}`}</span><span class="finance-risk risk-${risk.label.toLowerCase()}">Risco ${risk.label.toLowerCase()}</span></div>${risk.defaulted ? note('Pagamento não honrado. A perda está registrada no fechamento e fora da previsão de entradas.') : `<div class="finance-invoice-options"><section><h4>Cobrança</h4><p>Cordial: 0,5h de gestão. Firme: 1h e −1 de reputação, com recebimento imediato após o vencimento.</p><div class="finance-button-row"><button data-collect="${escape(r.projectId)}" ${collect.ok ? '' : 'disabled'} title="${escape(collect.reason)}">Cobrar cordialmente</button><button data-finance-action="firm" data-finance-project="${escape(r.projectId)}" ${firm.ok ? '' : 'disabled'} title="${escape(firm.reason)}">Cobrar firme</button></div>${!collect.ok ? note(collect.reason) : ''}</section><section><h4>Renegociar prazo</h4><p>Mais prazo e menos risco. Desconto de 2% (${money(renegotiate.fee)}) e 0,5h de gestão. Uma negociação por título.</p><form data-finance-form="renegotiate" data-finance-project="${escape(r.projectId)}"><select name="extension" aria-label="Novo prazo para ${escape(r.client)}"><option value="3">+3 dias</option><option value="7">+7 dias</option></select><button type="submit" ${renegotiate.ok ? '' : 'disabled'} title="${escape(renegotiate.reason)}">Renegociar</button></form>${!renegotiate.ok ? note(renegotiate.reason) : ''}</section><section class="finance-factoring"><h4>Antecipar recebível</h4><p>O banco assume o risco. Desconto de <b>${percent(anticipate.discountRate)}</b> (${money(anticipate.fee)}). Usa 0,5h de gestão.</p><strong>${money(anticipate.net)} líquidos hoje</strong><button data-finance-action="anticipate" data-finance-project="${escape(r.projectId)}" ${anticipate.ok ? '' : 'disabled'} title="${escape(anticipate.reason)}">Antecipar ${money(anticipate.net)}</button>${!anticipate.ok ? note(anticipate.reason) : ''}</section></div>`}</article>`;
  }).join('') || empty('Nenhum título emitido. Entregue um projeto para gerar um recebível; o dinheiro só entra na data combinada.')}${note('Qualidade ruim e atrasos de entrega elevam o risco. Clientes de alto risco podem dar calote. Melhorias do Financeiro reduzem riscos e atrasos; renegociar reduz o risco e antecipar transfere o risco ao banco.')}`;
}
function payables(state, data) {
  const office = getOfficeOverview(state), payroll = getPayroll(state);
  const sums = {};
  data.forecast.daily.flatMap(d => d.events).filter(e => e.amount < 0).forEach(e => sums[e.category] = (sums[e.category] || 0) - e.amount);
  const rows = Object.entries(sums).map(([key, value]) => ({ label: EXPENSE_LABELS[key] || key, value }));
  const due = key => data.forecast.daily.find(d => d.events.some(e => e.category === key))?.day;
  return `<div class="finance-page-heading"><h2>A pagar</h2><span>Débitos previstos em 30 dias</span></div><section class="finance-paper">${bars(rows)}${note('Débitos automáticos ao fechar os dias. Salários e encargos só nos dias úteis; aluguel e serviços todos os dias. Manutenção e impostos seguem o vencimento indicado.')}</section><div class="finance-two-columns"><section class="finance-paper"><h3>Folha e encargos</h3><div class="finance-compact-metrics">${metric('Salários / ciclo', money(payroll.salary))}${metric('Encargos / ciclo', money(payroll.charges))}${metric('Custo total da equipe', money(payroll.total))}</div><div class="finance-table-wrap"><table class="finance-table"><thead><tr><th>Pessoa</th><th>Contrato</th><th>Salário</th><th>Encargos</th></tr></thead><tbody>${payroll.rows.map(p => `<tr><td>${escape(p.name)}</td><td>${p.contract}</td><td>${money(p.salary)}</td><td>${money(p.charges)}</td></tr>`).join('') || '<tr><td colspan="4">Sem funcionários contratados.</td></tr>'}</tbody></table></div>${note('Modelo simplificado: CLT acrescenta 70% e PJ 15%. O total é distribuído em 20 dias úteis por ciclo de 28 dias. Contratar afeta o caixa além do salário anunciado.')}</section><section class="finance-paper"><h3>Espaço e tributos</h3><dl class="finance-facts"><div><dt>Aluguel · ${escape(office.stage.name)}</dt><dd>${money(office.dailyRent-35)}/dia</dd></div><div><dt>Internet e serviços</dt><dd>R$ 35/dia</dd></div><div><dt>Manutenção de computadores e salas</dt><dd>${money(office.monthlyMaintenance)} · D${office.nextMaintenanceDay}</dd></div><div><dt>Impostos provisionados</dt><dd>${money(state.finance.taxAccrued)} · D${state.finance.taxDueDay}</dd></div><div><dt>Imposto sobre faturamento</dt><dd>${percent(TAX_RATE)}</dd></div></dl>${note(`Impostos são provisionados ao faturar novas entregas e receita de produto; não incidem sobre empréstimos. Próximo débito tributário: D${due('tax') || state.finance.taxDueDay}. Melhorias têm manutenção e aluguel contínuos.`)}</section></div>`;
}
function credit(state, data) {
  const loan = getCreditOverview(state), maxPayment = Math.max(0, Math.min(state.cash, loan.balance));
  const debt = data.forecast.daily.at(-1)?.debt || loan.balance;
  return `<div class="finance-page-heading"><h2>Crédito e antecipação</h2><span>Ficha bancária da empresa</span></div><div class="finance-compact-metrics">${metric('Limite aprovado', money(loan.limit), 'Reputação + faturamento recebido + entregas')}${metric('Disponível', money(loan.available))}${metric('Dívida atual', money(loan.balance), `${percent(loan.interest)} por ciclo de 28 dias`, loan.balance > loan.limit ? 'danger' : '')}</div><div class="finance-two-columns"><section class="finance-paper"><h3>Capital de giro</h3><p>Reputação: <b>${Math.round(state.reputation)}/100</b> · Entregas: <b>${state.stats.delivered}</b> · Receita recebida: <b>${money(state.stats.revenue)}</b></p><form data-finance-form="borrow"><label>Valor do empréstimo<input name="amount" type="number" min="1" max="${loan.available}" step="0.01" value="${Math.min(2000, loan.available)}" required ${loan.available < 1 ? 'disabled' : ''}></label><button type="submit" ${loan.available < 1 ? 'disabled' : ''}>Contratar crédito</button></form><button data-action="take-loan" ${loan.available < 1 ? 'disabled' : ''}>Contratar ${money(Math.min(2000, loan.available))}</button>${note(`Próximos juros: ${money(loan.nextInterest)} em D${loan.nextInterestDay}. Juros são incorporados à dívida, não retirados do caixa. Amortizar libera limite; novos saques não adiam o vencimento dos juros.`)}</section><section class="finance-paper"><h3>Amortização</h3><form data-finance-form="repay"><label>Valor para pagar<input name="amount" type="number" min="1" max="${maxPayment}" step="0.01" value="${Math.min(500, maxPayment)}" required ${maxPayment < 1 ? 'disabled' : ''}></label><button type="submit" ${maxPayment < 1 ? 'disabled' : ''}>Amortizar dívida</button></form><button data-action="repay-loan" ${loan.balance <= 0 || state.cash < loan.balance ? 'disabled' : ''}>Quitar ${money(loan.balance)}</button>${bars([{ label: 'Dívida hoje', value: loan.balance }, { label: 'Dívida em 30 dias', value: debt, color: '#ae795a' }])}${debt > loan.balance ? '<div class="finance-warning">Sem amortização, os juros alimentam a dívida. Crédito usado para manter a operação pede um plano de saída.</div>' : ''}</section></div><section class="finance-paper"><h3>Antecipar em vez de tomar empréstimo</h3><p>Receba uma nota já emitida com desconto. O valor líquido depende do prazo e do risco do cliente; a nota é liquidada uma única vez.</p><button data-station-tab="receivables">Escolher recebível ${icon('arrow')}</button></section>`;
}
function monthly(state, selectedPeriod) {
  const id = selectedPeriod || periodId(state.day), statement = getMonthlyStatement(state, id), p = statement.current, previous = statement.previous;
  const comparison = (current, before) => previous ? signMoney(current - before) : '—';
  const rows = [['Receita faturada', p.revenue, previous?.revenue ?? 0], ...Object.entries(EXPENSE_LABELS).map(([key, label]) => [label, -p.expenses[key], -(previous?.expenses[key] || 0)]), ['Lucro / prejuízo', p.profit, previous?.profit ?? 0]];
  return `<div class="finance-page-heading"><h2>Fechamento mensal</h2><select data-finance-period aria-label="Ciclo do fechamento">${state.finance.periods.slice().reverse().map(entry => `<option value="${entry.id}" ${entry.id === id ? 'selected' : ''}>Ciclo ${entry.id} · D${entry.startDay}–D${entry.endDay}${entry.closed ? ' · fechado' : ' · em andamento'}</option>`).join('')}</select></div><div class="finance-compact-metrics">${metric('Receita faturada', money(p.revenue))}${metric('Despesas', money(p.costs))}${metric(p.profit >= 0 ? 'Lucro' : 'Prejuízo', money(p.profit), previous ? `Variação: ${comparison(p.profit, previous.profit)}` : 'Primeiro ciclo disponível', p.profit < 0 ? 'danger' : '')}</div><section class="finance-paper"><div class="finance-section-title"><h3>DRE simplificada · ${p.closed ? 'Fechada' : 'Parcial'}</h3><span>D${p.startDay} — D${p.endDay}</span></div>${bars([{ label: 'Receita faturada', value: p.revenue }, { label: 'Despesas', value: p.costs, color: '#ae795a' }])}<div class="finance-table-wrap"><table class="finance-table finance-dre"><thead><tr><th>Categoria</th><th>Ciclo ${p.id}</th><th>${previous ? `Ciclo ${previous.id}` : 'Anterior'}</th><th>Variação</th></tr></thead><tbody>${rows.map(([label, value, before], i) => `<tr class="${i === 0 || i === rows.length-1 ? 'total' : ''}"><td>${label}</td><td>${signMoney(value)}</td><td>${previous ? signMoney(before) : '—'}</td><td>${comparison(value, before)}</td></tr>`).join('')}</tbody></table></div>${note('Receita é reconhecida na entrega e no produto, mesmo antes de receber. Empréstimos, amortizações e compras de equipamentos não compõem o lucro; são movimentos de caixa. Juros, impostos, descontos e perdas com clientes entram nas despesas. O fechamento ocorre a cada 28 dias.')}${state.finance.importedBeforeDay ? note(`Histórico importado até D${state.finance.importedBeforeDay}; os registros antigos disponíveis foram preservados. O novo imposto vale para faturamento registrado nesta versão.`) : ''}</section>`;
}
export function renderFinanceBoard(state, { section = 'main', selectedDay = null, selectedPeriod = null } = {}) {
  if (section === 'office') section = 'payables';
  const data = getFinanceOverview(state), next = data.upcoming[0];
  const content = section === 'forecast' ? forecast(state, data, selectedDay) : section === 'receivables' ? receivables(state)
    : section === 'payables' ? payables(state, data) : section === 'credit' ? credit(state, data)
      : section === 'monthly' ? monthly(state, selectedPeriod) : section === 'ledger' ? ledger(state) : overview(state, data);
  return `<div class="finance-board"><header class="finance-board-header"><div><span class="finance-pin"></span><small>${escape(state.profile.company)}</small><h1>Financeiro</h1></div><button class="finance-board-close" data-action="close-station" aria-label="Fechar quadro financeiro">${icon('close')}</button></header><div class="finance-board-summary">${metric('Caixa disponível', money(state.cash), 'Saldo atual', state.cash < 0 ? 'danger' : '')}${metric('Fôlego', `${data.runwayCapped ? '365+' : data.runway} dias`, 'Sem novas entradas', data.runway < 7 ? 'danger' : '')}${metric('Próximo movimento', next ? `D${next.day}` : 'Rotina diária', next ? `${money(next.incoming)} entradas · ${money(next.outgoing)} saídas` : 'Aluguel e folha')}</div><nav class="finance-board-tabs" aria-label="Seções do quadro financeiro">${SECTIONS.map(([id, label], index) => `<button data-station-tab="${id}" class="${section === id || section === 'ledger' && id === 'main' ? 'active' : ''}" aria-current="${section === id ? 'page' : 'false'}"><small>0${index+1}</small><span>${label}</span></button>`).join('')}</nav><div class="finance-board-pages" tabindex="0" data-finance-section="${section}">${content}</div><footer class="finance-board-footer"><span>Valores em reais · ciclo de ${FINANCE_CYCLE} dias</span><span>Consulta no quadro · tempo pausado</span></footer></div>`;
}
