import { escape, icon } from './ui.js';
import { createBuilding, BUILDING_SECTORS, BUILDING_BAYS, SECTOR_NAMES, BAY_NAMES, floorName } from './office-building.js';

export function createLayoutDraft(office) {
  const b=office.building||createBuilding();
  return { selected:'development', floor:b.location.floor, placements:structuredClone(b.placements) };
}
export function moveDraftSector(draft, floor, bay) {
  const old={...draft.placements[draft.selected]};
  const other=BUILDING_SECTORS.find(id=>id!==draft.selected&&draft.placements[id].floor===floor&&draft.placements[id].bay===bay);
  if(other)draft.placements[other]={...old,door:draft.placements[other].door};
  draft.placements[draft.selected]={...old,floor,bay};
}
export function renderLayoutEditor(state,draft,modal=false) {
  const b=state.office.building||createBuilding(), selected=draft.selected,p=draft.placements[selected], level=state.office.rooms[selected];
  const dirty=JSON.stringify(draft.placements)!==JSON.stringify(b.placements);
  return `<section class="layout-editor" aria-label="Editor da planta"><header class="plan-heading"><div><small>ESPAÇO & CIA. / PLANEJAMENTO</small><h2 id="${modal?'modal-title':'layout-editor-title'}">Planta do escritório</h2><p>Selecione um setor, depois o espaço onde ele ficará. Espaços ocupados trocam de lugar.</p></div><span class="plan-draft-status">${dirty?'Alterações por aplicar':'Planta atual'}</span></header><nav class="plan-floor-tabs" aria-label="Andares da planta">${Array.from({length:b.floors},(_,i)=>`<button data-layout-floor="${i}" class="${draft.floor===i?'active':''}" aria-pressed="${draft.floor===i}">${floorName(i)}</button>`).join('')}</nav><div class="plan-columns"><div><nav class="plan-sector-tabs" aria-label="Setor a organizar">${BUILDING_SECTORS.map(id=>`<button data-layout-sector="${id}" class="${selected===id?'active':''}" aria-pressed="${selected===id}">${escape(SECTOR_NAMES[id])}</button>`).join('')}</nav><div class="plan-blueprint"><div class="plan-blueprint-title">${escape(state.profile.company)} · ${floorName(draft.floor)}</div><div class="plan-bays">${BUILDING_BAYS.map(bay=>{
    const sector=BUILDING_SECTORS.find(id=>draft.placements[id].floor===draft.floor&&draft.placements[id].bay===bay),style=sector?state.office.rooms[sector]:'empty';
    return `<button class="plan-cell ${style} ${sector===selected?'selected':''}" data-layout-bay="${bay}" aria-label="Colocar ${SECTOR_NAMES[selected]} em ${BAY_NAMES[bay]} no ${floorName(draft.floor)}"><small>${BAY_NAMES[bay]}</small><strong>${sector?SECTOR_NAMES[sector]:'Espaço livre'}</strong><span>${style==='glass'?'Cômodo de vidro':style==='dedicated'?'Cômodo com porta':style==='partition'?'Divisórias':style==='empty'?'Disponível':'Espaço aberto'}</span>${sector?'<div class="plan-mini-furniture"><i></i><i></i><i></i></div>':''}<i class="plan-door door-${sector&&['open','partition'].includes(style)?draft.placements[sector].door:bay.startsWith('n')?'bottom':'top'}"></i></button>`;
  }).join('')}<div class="plan-central-corridor"><span>Corredor</span><div>${b.floors>1?'↕ Escadas':''}${b.elevator?'<br>▥ Elevador':''}</div></div><div class="plan-cross-corridor"><span>Circulação livre</span></div></div><div class="plan-support-row">${draft.floor===0?'Copa · Descanso · Loja · Diário · Laboratório':'Copa · Descanso · Estúdio de apoio'}</div></div></div><aside class="plan-inspector"><small>SETOR SELECIONADO</small><h3>${SECTOR_NAMES[selected]}</h3><dl><div><dt>Andar</dt><dd>${floorName(p.floor)}</dd></div><div><dt>Posição</dt><dd>${BAY_NAMES[p.bay]}</dd></div><div><dt>Tipo</dt><dd>${level==='glass'?'Sala de vidro':level==='dedicated'?'Sala dedicada':level==='partition'?'Divisórias':'Espaço aberto'}</dd></div></dl>${['open','partition'].includes(level)?`<h4>Abertura da divisória</h4><div class="plan-door-options">${[['top','Norte'],['right','Leste'],['bottom','Sul'],['left','Oeste']].map(([id,label])=>`<button data-layout-door="${id}" class="${p.door===id?'active':''}" aria-pressed="${p.door===id}">${label}</button>`).join('')}</div><p>${level==='open'?'A orientação ficará reservada para quando você instalar divisórias.':'A abertura muda no mapa; o restante da divisória mantém suas colisões.'}</p>`:'<p>Este cômodo tem uma porta voltada para o corredor. Entrar nela abre o interior da sala; a versão de vidro conserva essa circulação.</p>'}<div class="plan-note">Mesas, equipamentos e funcionários acompanham o setor. Os corredores e a circulação vertical são preservados.</div><button data-layout-reset="true">Restaurar distribuição inicial</button></aside></div><footer class="plan-editor-footer"><p>Reorganizar não cobra uma nova compra. Andares e tipos de sala são adquiridos na loja. Só <b>Aplicar planta</b> altera o escritório.</p><div><button data-layout-cancel="true">Cancelar</button><button class="shop-primary" data-layout-save="true" ${dirty?'':'disabled'}>${icon('save')} Aplicar planta</button></div></footer></section>`;
}
